# -*- coding: utf-8 -*-
"""deploy.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KXtYHKUfg5EuqaKLbWeB4VKftvCKDzTc
"""

# Import dependencies

#!pip install flask-ngrok
import numpy as np
import pandas as pd
import csv
from sklearn.linear_model import LinearRegression
import pickle
from flask import Flask,render_template,url_for,request
#from flask_ngrok import run_with_ngrok


#Create training dataset first as csv and then as dataframe

header=['Experience','Test_score','Interview_score','Salary']
data=[['zero',8,9,50000],
      ['zero',8,6,45000],
      ['five',6,7,60000],
      ['two',10,10,65000],
      ['seven',9,6,70000],
      ['three',7,10,62000],
      ['ten',7,7,72000],
      ['eleven',7,8,80000]]

with open('hiring.csv','w',newline='') as f:
  writer=csv.writer(f,delimiter=',')
  writer.writerow(header)
  writer.writerows(data)

ds=pd.read_csv('hiring.csv')

txt2num={'one':1,'two':2,'three':3,'four':4,'five':5,
         'six':6,'seven':7,'eight':8,'nine':9,'ten':10,
         'eleven':11,'zero':0}

ds.Experience=ds.Experience.map(txt2num)


# Train and serialize sklearn predictor

X=ds.iloc[:,:3].to_numpy()
y=ds.iloc[:,-1].to_numpy()

reg=LinearRegression()
reg.fit(X,y)
pickle.dump(reg,open('model.plk','wb'))

p_reg=pickle.load(open('model.plk','rb'))

# Flask backend
# Attention: Here you will have to adjust the path of the template_folder
# according to your directory tree

app=Flask(__name__,template_folder='C:/Users/cafros/PycharmProjects/MLPython/flask_skl_salary')
#run_with_ngrok(app)

@app.route('/')
def home():
  return render_template('index.html')

@app.route("/predict", methods=['POST'])
def predict():
  exp=int(request.form.get('exp'))
  tsc=int(request.form['tsc'])
  inc=int(request.form['inc'])
  X=np.array([[exp,tsc,inc]])
  pred=int(p_reg.predict(X).item())
  return render_template('index.html',prediction=f'Predicted Salary: {pred:.0f}')


if __name__=='__main__':
  app.run()